### ISSUE TITLE
Command Interruption

### ISSUE THREAD

**Issue by HamishWHC** [insou22/mipsy#112]
It would be useful to be able to interrupt execution of step2syscall or step2input commands with Ctrl-C or other combination. I'm using mipsy to find where the infinite loop is in my code, so I want to interrupt once I find it!

Looking at the source, it seems doable by adding a Ctrl-C signal listener around the loop here: https://github.com/insou22/mipsy/blob/main/crates/mipsy_interactive/src/interactive/commands/step2syscall.rs#L26, although a better implementation might be to add this as a wrapper around all commands (or if that causes issues, a flag in the command config that says to allow interruption).

**Comment by Dylan-Brotherston** [comment]
implementing a Interrupted error [here](https://github.com/insou22/mipsy/blob/e21a5dfa734d241a23be2fed8c3d7aa02fbb3a6d/crates/mipsy_interactive/src/interactive/error.rs#L8) and returning a `CommandResult<T, Interrupted>` from `state.step()` should enable this behavior for all `step*` commands.

**Comment by Dylan-Brotherston** [comment]
@insou22 Can this be looked into again AndrewT is "unimpressed"

**Comment by joooooooooooooooooooooooooooooooooooosh** [comment]
Putting the listener around `step` or `eval_stepped_runtime` would make it applicable to all interactive commands e.g. `run`, `step2input`, etc but a) would require setting up and cleaning up the listener on every instruction and b) exposes the possibility of the interrupt signal being received during mipsy code outside of `step`,  especially in `step2input` where there is a bit of extra code in the loop

I think the easiest option would be having a separate listener around each commands event loop, such as [here](https://github.com/insou22/mipsy/blob/main/crates/mipsy_interactive/src/interactive/commands/step2input.rs#L32) and [here](https://github.com/insou22/mipsy/blob/main/crates/mipsy_interactive/src/interactive/commands/step2syscall.rs#L31)

**Comment by Dylan-Brotherston** [comment]
`step` commands will eventually terminate, so they aren't as big an issue.
`run` is the main issue as it is possible for it to never terminate.

**Comment by joooooooooooooooooooooooooooooooooooosh** [comment]
`step` commands won't necessarily terminate if there's an infinite loop before any input/syscall
