### ISSUE TITLE
Feature Request: Ignoring Breakpoints

### ISSUE THREAD

**Issue by Varun-Sethu** [insou22/mipsy#115]
It would be cool if there was a way to ignore a breakpoint n times, similar to GDB's ignore command. This would really help with debugging nested loops with several iterations. 

It seems doable by extending https://github.com/insou22/mipsy/blob/main/crates/mipsy_lib/src/compile/mod.rs#L38 to a HashMap of addresses and remaining hit counts and modifying this condition: https://github.com/insou22/mipsy/blob/main/crates/mipsy_interactive/src/interactive/mod.rs#L409 to take into account the remaining hit counts?

**Comment by insou22** [comment]
Sure, seems reasonable to me!
