### ISSUE TITLE
MIPS32 ISA registers do not need to be initialised

### ISSUE THREAD

**Issue by xdrr** [insou22/mipsy#116]
## Issue

Mipsy throws an uninitialised memory error when an instruction reads from a register that hasn't been written to in the scope of the simulator. This should not occur as MIPS32 ISA registers do not require initialisation. The register file should be zeroed after power on.

### Reproduction

Instruction idioms such as the following will cause the exception to be thrown:

```mips
.text
main:
        xor $t0, $t0, $t0
        jr $ra
```

```
error: your program tried to read uninitialised memory
the instruction that failed was:
0x00400000 3   [0x01084026]    xor    $t0, $t0, $t0     #  xor $t0, $t0, $t0

this happened because $t0 was uninitialised.
| note: $t0 was never initialised
```

**Comment by Dylan-Brotherston** [comment]
Hi @xdrr 

This is incorrect.
The MIPS ABI from the Linux foundation specifies that:

> Except as shown below, general integer and floating-point register values are un-specified at process entry.
> Consequently, a program that requires specific register values must set them explicitly during process initialization. It should not rely on the operating system to set all registers to 0.
> $v0 A non-zero value specifies a function pointer the application should register with atexit(BA_OS). If $v0 contains zero, no action is required.
> $sp The stack pointer holds the address of the bottom of the stack, which must be doubleword (8 byte) aligned.
> $ra The return address register is set to zero so that programs that search backward through stack frames (stack backtracing) recognize the last stack frame, that is, a stack frame with a zero in the saved $31 slot.

MIPSY doesn't pass $v0 as 0, but all other register abide by this standard.

**Comment by Dylan-Brotherston** [comment]
This information is from page "3-31" of https://www.google.com/url?sa=t&source=web&rct=j&url=https://refspecs.linuxfoundation.org/elf/mipsabi.pdf&ved=2ahUKEwjfx8TaoN_zAhVUCRAIHaJkDlAQFnoECAQQAQ&sqi=2&usg=AOvVaw3kzCsAT5eQCfXChYusAJjP
