### ISSUE TITLE
missing pseudo-instruction `NOT $R, Imm`

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#117]

**Comment by Qantas94Heavy** [comment]
Ah, turns out SPIM doesn't support using immediates with `NOT`, should mipsy still support this for consistency with other instructions?

**Comment by Dylan-Brotherston** [comment]
MIPSY implements many pseudo-instructions that SPIM doesn't.

**Comment by insou22** [comment]
yep this is not an issue for us
