### ISSUE TITLE
No distinction between uninitialized and unprintable values in in the mipsy-web "data" tab

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#148]
![Screenshot 2022-02-24 160405](https://user-images.githubusercontent.com/22044664/155461368-b63ca59d-0967-4dca-ba5e-e29a804407a8.png)
`\n` and `\0` are shown as `_`
the same as uninitialized memory.

**Comment by insou22** [comment]
I experimented with a few different formats for this and everything I tried looked really bad and made it far harder for me to read ...

any suggestions @Dylan-Brotherston ?

**Comment by Dylan-Brotherston** [comment]
![Screenshot 2022-02-24 164922](https://user-images.githubusercontent.com/22044664/155465915-11ee1b48-1ecf-4907-b4f3-d27b974bf952.png)

Escape sequences, when available, don't look that bad.
If not available tools like hexdump use `.`

**Comment by SpanishPear** [comment]
I believe this has been fixed in #180
