### ISSUE TITLE
final `jr` not highlighted in mipsy-web

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#152]
```asm
main:
    li $t0, 1
    li $t1, 1
    li $t2, 1
    li $t3, 1

    li $v0, 0
    jr $ra
```
when stepping the above code `li $v0, 0` is the last instruction highlighted in the "decompiled" tab.

**Comment by SpanishPear** [comment]
this was me doing the quick soln of highlight = instr - 4, but that wont work for obvious reasons when it comes to the end of the user segment. 

willfix.
