### ISSUE TITLE
Create secondary register tab

### ISSUE THREAD

**Issue by SpanishPear** [insou22/mipsy#153]
with mipsy web & students new to the MIPS I'm worried the concept that there is a bank of 32 registers isn't obvious

but in tandem its better not to cognitively overload them - so showing relevant registers is good - maybe two tabs - all registers & - registers changed since reaching main:??

and include register numbers in one or both tabs??

definitely worth having a separate tab for *all* registers

**Comment by Dylan-Brotherston** [comment]
Instead of a separate tab I would suggest this be included in a "register configuration" menu:

defined/changed/all register 
register numbers/register names.
base 2/10/16/ascii values.

**Comment by SpanishPear** [comment]
@abiramen  assigned you this one for now. 

**Scope**
  * Migrate the current contents of the `Registers` component to a new component,  to be called `UsedRegistersTab` 
  * Create `AllRegistersTab` component, which shows all registers
  * Add some `DisplayedRegisterTabState` - a boolean (or `enum` to future proof) to determine what register tab is being shown
  * in the `Registers` component, either render the `AllRegistersTab` or the `UsedRegistersTab` depending on the current value of `DisplayedRegisterTabState`
  * Add the clicking tabs (a la rest of mipsy web) to switch between all registyers/used registers 


Later on, this can be a configurable, but we can show as two tabs for now.
