### ISSUE TITLE
Better saving on mipsy-web

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#156]
Some devices, like phones, cannot easily send a control-S so a button for saving would be useful.

Additionally, some operating systems (macOS) use command-S instead of control-S in native applications and mipsy-should try and accommodate for this.

**Comment by SpanishPear** [comment]
https://github.com/insou22/mipsy/blob/main/crates/mipsy_web/src/components/navbar.rs

Should be a quick fix if you want to take a try, just add the icon and the required callback. 

The callback would look similar to `save_keydown` inside app.rs

**Comment by Dylan-Brotherston** [comment]
closed by #165
