### ISSUE TITLE
input `syscall`s are only highlighted after blocking is compleate not during blocking in mipsy-web

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#164]
During I/O blocking the instruction before syscall is highlighted, even thou the currently executing instruction is the syscall.
![image](https://user-images.githubusercontent.com/22044664/155993547-15cad209-5ee3-4173-853b-74cf60d0e897.png)

**Comment by SpanishPear** [comment]
The highlighting shows the execution that has just finished, as per the previous issue who's number I cannot see.

While we are io blocking, the syscall instruction has not yet finished, and hence the instruction does not highlight.

I could add a workaround special case for syscalls, but I'm not sure this is good UX

**Comment by SpanishPear** [comment]
Update, workarounds are quite technically challenging, as `mipsy` is built around the idea that there is no currently "running" instruction. This is probably a wontfix.
