### ISSUE TITLE
files loaded from local storage in mipsy-web must be saved before they compile but to not indicate this

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#166]
files loaded from local storage don't have `- [unsaved]` added to their name but behave as if they were unsaved.
![image](https://user-images.githubusercontent.com/22044664/155995223-a3a8722d-5415-474b-8bcb-34b3c5a7534a.png)

**Comment by SpanishPear** [comment]
worked locally but seems to be playing up on live... reopening for now.
