### ISSUE TITLE
Register values in other representations

### ISSUE THREAD

**Issue by abiramen** [insou22/mipsy#213]
Currently the values in the register tabs are only displayed as hexadecimal.

While this is useful considering the fixed width, this provides an extra barrier for students, especially as we don't properly cover hexadecimal until later weeks of the course besides some vague handwaving. Options should be available to display the contents of registers in other representations (primarily decimal and ascii), with individual registers being toggleable.

**Comment by SpanishPear** [comment]
Is per register representation useful?

**Comment by abiramen** [comment]
> Is per register representation useful?

Perhaps? There might be a case where a student only wants to see an ascii representation of an individual register, say `$a0` for a print_char syscall, while other registers may contain values which make absolutely no sense in ascii.

Closing due to dup.
