### ISSUE TITLE
mipsy_web doesn't break on breakpoints that are set directly after a syscall

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#246]
![image](https://user-images.githubusercontent.com/22044664/191776396-0748e1d9-8bef-46f9-b0ac-8650ba8fab58.png)
This program ran to completion despite the breakpoint.

**Comment by SpanishPear** [comment]
Note to self: only occurs on a manually set breakpoint, not a `break` instruction
