### ISSUE TITLE
watchpoints in mipsy_web

### ISSUE THREAD

**Issue by joooooooooooooooooooooooooooooooooooosh** [insou22/mipsy#250]
now that watchpoints are a part of `mipsy_lib`, having mipsy_web be able to break on the reading/changing of a register would be useful. Adding buttons for watchpoints in the used/all registers tab would probably be most intuitive

**Comment by SpanishPear** [comment]
have fun!

**Comment by joooooooooooooooooooooooooooooooooooosh** [comment]
💀 what is a web and why does mipsy have one
