### ISSUE TITLE
misleading error messages on uninitialised register use

### ISSUE THREAD

**Issue by joooooooooooooooooooooooooooooooooooosh** [insou22/mipsy#252]
```
main:
la $t0, a
lb $t1, ($t0)
li $t0, 5
move $t2, $t1

.data
a: .space 1
```
Running this in mipsy correctly identifies use of uninitialised register and points out that line 3 caused it to be uninitialised, but it reports the value of $t0 as the current value of 5 instead of the value at the time which was 0x10010000

**Comment by insou22** [comment]
wow really!!? that's not ideal lol
