### ISSUE TITLE
[SIP] Arithmetic overflow

### ISSUE THREAD

**Issue by insou22** [insou22/mipsy#3]
SPIM's default exception message for an arithmetic overflow offers little context for students.

# Example

## MIPS input:
```
main:
	li		$t0, 0x7FFFFFFF
	li		$t1, 0x1

	add		$t0, $t0, $t1
	jr		$ra
```

## SPIM output:
```
❯ spim -f foo.s
Loaded: /home/zac/uni/teach/comp1521/20T2/work/spim-simulator/CPU/exceptions.s
Exception occurred at PC=0x00400030
  Arithmetic overflow
  Exception 12  [Arithmetic overflow]  occurred and ignored
```

# Suggested improvements

- Explain that the error was an arithmetic overflow
- Tell the student the instruction responsible
- Display the context of the error - eg. the registers involved, and their current values
- Show what the expected and actual result would be, like DCC
- Tell the student to use an unsigned instruction variant if they would like to intentionally ignore overflow

# Other notes?

**Comment by Dylan-Brotherston** [comment]
# Suggested improvements
Show what the expected and actual result would be. like DCC.

**Comment by insou22** [comment]
> # Suggested improvements
> Show what the expected and actual result would be. like DCC.

Added
