### ISSUE TITLE
break on line

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#39]
The current help for the `breakpoint` command says that a breakpoint must be created at an `address`.
```
<address> may be: a decimal address (`4194304`), a hex address (`0x400000`), or a label (`main`).
```
This works well for addresses at/near labels
eg:
```
breakpoint insert main
breakpoint insert loop
breakpoint insert fuct1 + 2
```
but many lines will not be near a label and it would be easier to refer to them by line number.
If multiple files are loaded then the overlapping section of line numbers would need to be refereed to be file and line.

Proposed syntax:
`:<line>` for line number (to differentiate from decimal address)
`<file>:<line>`

E.G.

```
breakpoint insert :20
breakpoint insert hello_world.c:7
```

**Comment by joooooooooooooooooooooooooooooooooooosh** [comment]
note for myself - even the `breakpoint insert fuct1 + 2` syntax isn't currently supported, look into this
