### ISSUE TITLE
move step command to a hierarchical menu

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#47]
At the moment there are 4 step commands, `step`, `back`, `step2input`, `step2syscall`
This would remove  `step2input` and `step2syscall` making them sub-commands for `step`

Personally i think a hierarchical menu is better for this type of program.

`step` for single step (we have this)
`step N` for multiple step (we have this)
`step -N` for backwards step (but still having `back` or `pets` is a good alias) (also `back -N` as an alias for `step N`)

but also having

`step syscall`
`step syscall TYPE` (`step syscall input` or `step syscall output` or `step syscall integer` or `step syscall string, ect.`)
`step breakpoint` (which is different to run)
`step instruction <inst>` (`step instruction jal` or `step instruction jr` (as the two most useful))
(`step instruction syscall` same as `step syscall`)

**Comment by joooooooooooooooooooooooooooooooooooosh** [comment]
what would differentiate `step breakpoint` from `run`?
