### ISSUE TITLE
Rem doesn't accept second source register, only immediate values

### ISSUE THREAD

**Issue by evan-a-w** [insou22/mipsy#52]
![image](https://user-images.githubusercontent.com/53632406/135742624-0366ffe5-f552-43b5-8dcf-be4a40360512.png)

**Comment by Dylan-Brotherston** [comment]
It existed yesterday #35

**Comment by evan-a-w** [comment]
Yeah I actually had an outdated version of mipsy - installed last week or so. Works in current version, sorry.

**Comment by insou22** [comment]
Ah no problem, thanks anyways!
