### ISSUE TITLE
Directives in the .text segment 

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#56]
Mipsy currently doesn't allow directives like `.space`, `.byte`, `.half`, `.word`, `.float`, `.double`, `.ascii` or `.asciiz` in the `.text` segment. Or for instructor in the `.data` segment.

This is currently intentional to avoid a panic, but in some very niche cases this behaviour is desirable. (see: https://cgi.cse.unsw.edu.au/~cs1521/21T3/lab/04/questions)

A workaround for the first issue is to spam `nop` instructions as a substitute for `.space` where you want the empty space in the `.text` segment.
---

Reported by Matthew Richards on COMP1521 course forum.

**Comment by insou22** [comment]
mipsy now allows directives in the text segment
