### ISSUE TITLE
missing instruction ANDI

### ISSUE THREAD

**Issue by Dylan-Brotherston** [insou22/mipsy#67]
```
  --> /dev/stdin:12:5
   |
12 |     ANDI  $t1, 2
   |     ^^^^^^^^^^^^ unknown instruction `ANDI`
```

Note: 3 argument form does exist.

**Comment by Dylan-Brotherston** [comment]
we are for all other instructions.
At the moment it being missing is non-standard.
Removal of all of them is a discussion for later.

**Comment by insou22** [comment]
yeah that's just me forgetting to put it on a whole class of instructions -- very simple fix though
this issue also applies to
- SLTI[U]
- ORI
- XORI
- maybe others
