### ISSUE TITLE
Unhelpful error when using .align directive in .text section

### ISSUE THREAD

**Issue by AntarcticanWaffles** [insou22/mipsy#86]
When .align is used in .text section, mipsy refuses to run the program with a rather unhelpful message
"error: could not find instruction at 0x80000000"
A better warning message would be appreciated

Spim has bizarro behavior in this situation:
```
    .text
my_label:
    .align 2
    .space 2048
```
my_label will be placed in .data.
Probably should not be replicated

Here is a file annotating some of spim's behavior in this situation
[text_data.s.txt](https://github.com/insou22/mipsy/files/7309373/text_data.s.txt)

**Comment by insou22** [comment]
I believe mipsy should behave correctly in this scenario now -- feel free to double check and let me know if I've missed anything.

Thanks for the report!
